- bot.py
Are you able to cherry-pick which changes you want implemented?
Or is it better approach to have more and smaller commits being pushed?
Anyway, here are the changes...
- Added a dictionary with all relevant IDs and updated code to use that.
- Added command to delete user command before bot executes the command, but mention their name in the final output (select commands to be deleted at top)
- Removed FluffM as the default user in the list.
- Bot responds to !whos_LFG with a list of users available for playing when more than one are.
- Added some aliases to commands to cover for variations
- Added !no_lfg command to remove a user from the list, if he is in it
- Checking of the online/offline status of members before listing them as available
- Restrict the usage of the LFG commands to the …
> Updates to current bot, mainly tackling some current issues

- bot.py
- utils.py
First time using the discord API, OSR API, and doing a git pull request :)
100% untested though sorry - just worked backwards from the rest of your code.
> Adding ranks to !go message (and refactoring with get_user)

- bot.py
- utils.py
extra brackets on rank info, missing space between name and rank, missing l in 'follow'
Could use .format() for the long message with multiple variables, but possibly not worth changing?
> fix minor text problems

- bot.py
I'd like to make this a bit cleaner, but didn't have much time. Let's get it out and tested. :)
Will work more on it in the week.
> Make `help` contectual and add `league` for info on OSR leagues.

- bot.py
Not a clue how to catch that `CommandNotFound` exception. The `process_commands` function catches it and then calls a `command_error` event. I have not figured out how to listen to it, though. Even if I did, it probably wouldn't have access to the offending message, so this might be for the better anyway.
I also took the liberty to refactor a little.
> Fix "Unknown command" message

- bot.py
Reverts climu/OSR-discord-bot#34
> Revert "Fix "Unknown command" message"

- bot.py
Less repetition of code. Also makes it a lot easier to add more picture commands in the future, or remove existing ones.
Btw, `!yuta` and `!chang_ho` are the same image...
> Refactor picture commands

- bot.py
- config.py
- utils.py
Requires #38 - I'll fix it up and make it mergeable after that gets merged
> Add emoji interface to !who

- bot.py
- utils.py
Also changed messages to embeds, and added 'Requested by:' to footer
> Add links to OGS/KGS profiles

- config.py
> Fix member role ID

- bot.py
To ensure consistency amongst commands, and to help prevent spam (especially with long text commands)
Could probably be refactored somehow?
> Adding "Req'd by" to all commands

- README.md
- bot.py
- config.py
Fixed issue #45 
Added quote functionality as !quote msg_id response
Updated readme file
> Fix issue with duplicate user greetings and added quote functionality

- bot.py
- config.py
- Removed bot responses to `!go` and `!no go`
- Removed ability to list users in @player group (too big)
- Removed expiraion time options and loop to check for expiration time.
- Added a command to assign all users the "player" role (will need removing as soon as first command has fired.]
- Resolved issue #47 
- Other small edits
> Major update regarding usage of "player" role

- config.py
Forgot to add the delete option
> Delete discord message `!goquest`

- bot.py
- utils.py
Add OSR account in `!who` - Closes issue #51 
Fix image `!yuta` - Closes issue #52 - Will need re-writing in the future as image link is at two places
Fix spacing in `!list`- Closes issue #54
> Add OSR account in `!who`, fix `!yuta` and `!list`

- bot.py
Will need future work and writing the code a bit better to split to any number of messages (not just two).
> Split message when longer than 2048 characters and add idle users number

- bot.py
- config.py
Add '9x9' role managment commands and update help file
> Add '9x9' role managment commands and update help file

- bot.py
- config.py
Add '9x9' role managment commands and update help file
> Rename from '9x9' to 'nine'

- bot.py
- config.py
Reverts climu/OSR-discord-bot#66
> Revert "Rename from '9x9' to 'nine'"

- README.md
- bot.py
- kgs.py
- Rename `LFG_TOKEN` to `OSR_TOKEN`
- Introduce KGS username `OSRbot` as an environment variable `KGS_USERNAME`
- Introduce KGS password `######` as an environment variable `KGS_PASSWORD`
> Update token environment variables for Discord token and KGS credentials

- bot.py
- config.py
- kgs.py
Remove old code related to removing access to local file for KGS password
Fix issue #70
> Remove old code and fix `!nine` command

- bot.py
Reverts climu/OSR-discord-bot#79
matplotlib not installed on venv
> Revert "Add OGS rank graph to `!rank <username>`"

- bot.py
- requirements.txt
> Add OGS rank graph to `!rank <username>`

- utils.py
In response to https://discordapp.com/channels/287487891003932672/287487891003932672/546304767375179828
> Add local time on `!who` message

- .gitignore
- README.md
- bot.py
- Handles the case where user attempts to use !who with a mention, like `!who @seequ`
- Add short setup documentation, answering the questions I had.
- gitignore for files we *definitely* don't want anyone to commit
> Support mentions in !who command
